### ISSUE TITLE
TargetPlatform.fuchsia is not yet supported

### ISSUE THREAD

**Issue by ikhwanizao** [Ashwinbicholiya/Food-delivery-app#10]
Hi, I ran the code but got an error after trying to pay for food. It says TargetPlatform.fuchsia is not yet supported by the maps plugin

**Comment by Ashwinbicholiya** [comment]
Yes because it's try to locate the user location by using gps.

**Comment by ikhwanizao** [comment]
> Yes because it's try to locate the user location by using gps

meaning if i enable gps it will run?

**Comment by Ashwinbicholiya** [comment]
The problem was a line of code in main.dart:

debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;

Add this line and your issue is solved.

**Comment by ikhwanizao** [comment]
Thank you very much, sir. It works now. One more question if you don't mind me asking. I'm quite new to Flutter, could you please guide me on how I can add new food? I have tried adding new food to firebase but it does not appear. Thank you again

**Comment by Ashwinbicholiya** [comment]
You can check file called addproduct.dart for adding new product in Firebase database in the cart and this cart will retrieve the database that you add.
You can also check my scanpay repository there i have done this in a perfect manner.

**Comment by ikhwanizao** [comment]
Thank you, sir I will check it out. Have a wonderful day.
