### ISSUE TITLE
Delete order and three-bar icon does not work

### ISSUE THREAD

**Issue by ikhwanizao** [Ashwinbicholiya/Food-delivery-app#11]
Hi, after I added an order I wanted to delete it but the delete button(trash icon) does not do anything. Could you please assist me? Also, the three bar icon on the right does not do anything after I tapped on it.

**Comment by Ashwinbicholiya** [comment]
Drag and drop the item to the delete icon it will delete the item and the three bar icon it's just an UI it'll not do anything.
