### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by syah769** [Ashwinbicholiya/Food-delivery-app#3]
I don't know what happened. I'm using flutter 1.17 stable. Maybe its related with flutter version? 
![Screenshot 2020-05-23 at 11 32 41 AM](https://user-images.githubusercontent.com/37147869/82720820-b0751e80-9ce9-11ea-8097-1bd81f01f830.png)

**Comment by Ashwinbicholiya** [comment]
I don't know why you getting this problem.
Try this:
Create a new project and paste all this files into your new project.

**Comment by anddimario** [comment]
i've changed with:
```
      onLeave: (foodItem) {
        colorBloc.setColor(Colors.white);
      },
```
and now i can build the project, but i can't check if something changed in usability, here my flutter info:
```
Flutter is already up to date on channel stable
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (2 settimane fa) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2
```

**Comment by Ashwinbicholiya** [comment]
Your Flutteris up to date.
Try to run app on your device and check if there is an error.
