### ISSUE TITLE
Google services and firebase rules

### ISSUE THREAD

**Issue by anddimario** [Ashwinbicholiya/Food-delivery-app#4]
I think that this project could be useful for my little service in my city, but i think that it could be useful for forks and usage to put in gitignore the google-service.json and add docs about firebase rules (storage and cloudstore).

It could be useful to develop new features from fork using personal account, for example, i'm looking for firebase messages, or some functions

What do you think?

**Comment by Ashwinbicholiya** [comment]
It's great to add some changes.

**Comment by Ashwinbicholiya** [comment]
Sounds good !
