### ISSUE TITLE
passwords

### ISSUE THREAD

**Issue by prabu803** [Ashwinbicholiya/Food-delivery-app#8]
can you provide the password of admin

**Comment by Ashwinbicholiya** [comment]
Firebase login details?

**Comment by prabu803** [comment]
First I tried with apk,so I need login details for admin.

**Comment by Ashwinbicholiya** [comment]
There is no login details of admin.
You can sign up and login as a user.
Or you can login with your google account

**Comment by prabu803** [comment]
How to check admin process

**Comment by Ashwinbicholiya** [comment]
Please describe your issue 
What you want to do or trying to access?

**Comment by prabu803** [comment]
actually i'm trying to sign in/sign up as restaurant user,app get closed
while trying this process

**Comment by prabu803** [comment]
not able to sign up except sign in with google,if i'm trying the
application screen closed .please help it

**Comment by Ashwinbicholiya** [comment]
Your password should be at least 6 characters.

**Comment by prabu803** [comment]
signup key not enabled

**Comment by prabu803** [comment]
if possible you can try with same apk

https://drive.google.com/file/d/17dFLghpxs5x_lWXH_xyEmrzMMi4FT_8E/view?usp=drivesdk

**Comment by Ashwinbicholiya** [comment]
I got it 
First sign up after you pressed the sign up button the app will crash.
So Sign in with same email and pass because you successfully signed up in the app but the app crashes 
I will fix it later. 
And follow same in sign in as User.
